#pragma once

#define OPENGL

#include <stdint.h>
#include <cstdio>

#include "Lib/GLM/glm/glm.hpp"

#ifdef OPENGL
#define GLFW_DLL

#include "Lib/GLEW/include/GL/glew.h"

#ifdef _DEBUG
#define GX_CALL(x) x; { GLuint error = glGetError(); while(error != GL_NO_ERROR) { printf("ERREUR | %s(%i) : %i\n", __FILE__, __LINE__, error); error = glGetError(); }}
#endif
#ifdef _RELEASE
#define GX_CALL(x) x
#endif

#define VERTEX_SHADER GL_VERTEX_SHADER
#define FRAGMENT_SHADER GL_FRAGMENT_SHADER
#define GEOMETRY_SHADER GL_GEOMETRY_SHADER
#define COMPUTE_SHADER GL_COMPUTE_SHADER

#define FLOAT_TYPE GL_FLOAT
#define INT_TYPE GL_INT
#define UINT_TYPE GL_UNSIGNED_INT

#define BOOL_TRUE GLTRUE
#define BOOL_FALSE GL_FALSE

#define TEX_2D GL_TEXTURE_2D

#define TEX_RED GL_RED
#define TEX_GREEN GL_GREEN
#define TEX_BLUE_ GL_BLUE
#define TEX_ALPHA GL_ALPHA
#define TEX_RG GL_RG
#define TEX_RGB GL_RGB
#define TEX_BGR GL_BGR
#define TEX_RGBA GL_RGBA
#define TEX_BGRA GL_BGRA
#define TEX_REDI GL_RED_INTEGER
#define TEX_RGI GL_RG_INTEGER
#define TEX_RGBI GL_RGB_INTEGER
#define TEX_BGRI GL_BGR_INTEGER
#define TEX_RGBAI GL_RGBA_INTEGER
#define TEX_BGRAI GL_BGRA_INTEGER
#define TEX_LUMINANCE GL_LUMINANCE
#define TEX_LUMINANCE_ALPHA GL_LUMINANCE_ALPHA
#define TEX_STENCIL_INDEX GL_STENCIL_INDEX
#define TEX_DEPTH_COMPONENT GL_DEPTH_COMPONENT
#define TEX_DEPTH_STENCIL GL_DEPTH_STENCIL

#define TEX_FORMAT_RED TEX_RED
#define TEX_FORMAT_RG TEX_RG
#define TEX_FORMAT_RGB TEX_RGB
#define TEX_FORMAT_BGR TEX_BGR
#define TEX_FORMAT_RGBA TEX_RGBA
#define TEX_FORMAT_BGRA TEX_BGRA
#define TEX_FORMAT_REDI TEX_REDI
#define TEX_FORMAT_RGI TEX_RGI
#define TEX_FORMAT_RGBI TEX_RGBI
#define TEX_FORMAT_BGRI TEX_BGRI
#define TEX_FORMAT_RGBAI TEX_RGBAI
#define TEX_FORMAT_BGRAI TEX_BGRAI
#define TEX_FORMAT_STENCIL_INDEX TEX_STENCIL_INDEX
#define TEX_FORMAT_DEPTH_COMPONENT TEX_DEPTH_COMPONENT
#define TEX_FORMAT_DEPTH_STENCIL TEX_DEPTH_STENCIL

#define TEX_INFORMAT_RED TEX_FORMAT_RED
#define TEX_INFORMAT_RG TEX_FORMAT_RG
#define TEX_INFORMAT_RGB TEX_FORMAT_RGB
#define TEX_INFORMAT_RGBA TEX_FORMAT_RGBA
#define TEX_INFORMAT_DEPTH_COMPONENT TEX_FORMAT_DEPTH_COMPONENT
#define TEX_INFORMAT_DEPTH_STENCIL TEX_FORMAT_DEPTH_STENCIL
#define TEX_INFORMAT_RED TEX_FORMAT_RED

#define TEX_DEPTH24_STENCIL8 GL_DEPTH24_STENCIL8

#define FBO_COLOR_ATTACHMENT0 GL_COLOR_ATTACHMENT0
#define FBO_DEPTH_ATTACHMENT GL_DEPTH_ATTACHMENT
#define FBO_STENCIL_ATTACHMENT GL_STENCIL_ATTACHMENT
#define FBO_DEPTH_STENCIL_ATTACHMENT GL_DEPTH_STENCIL_ATTACHMENT

#define TEX_FILTER_NEAREST GL_NEAREST
#define TEX_FILTER_LINEAR GL_LINEAR

#define TEX_WRAP_REPEAT GL_REPEAT
#define TEX_WRAP_MIRRORD_REPEAT GL_MIRRORED_REPEAT
#define TEX_WRAP_CLAMP_BORDER GL_CLAMP_TO_BORDER
#define TEX_WRAP_CLAMP_EDGE GL_CLAMP_TO_EDGE

#define TEX_CUBEMAP_POSX GL_TEXTURE_CUBE_MAP_POSITIVE_X
#define TEX_CUBEMAP_NEGX GL_TEXTURE_CUBE_MAP_NEGATIVE_X
#define TEX_CUBEMAP_POSY GL_TEXTURE_CUBE_MAP_POSITIVE_Z
#define TEX_CUBEMAP_NEGY GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
#define TEX_CUBEMAP_POSZ GL_TEXTURE_CUBE_MAP_POSITIVE_Z
#define TEX_CUBEMAP_NEGZ GL_TEXTURE_CUBE_MAP_NEGATIVE_Z

#define STENCIL_FUNC_KEEP GL_KEEP
#define STENCIL_FUNC_REPLACE GL_REPLACE
#define STENCIL_FUNC_INCR GL_INCR
#define STENCIL_FUNC_DECR GL_DECR
#define STENCIL_FUNC_ZERO GL_ZERO
#define STENCIL_FUNC_INCR_WRAP GL_INCR_WRAP
#define STENCIL_FUNC_DECR_WRAP GL_DECR_WRAP

#define FUNC_EQUAL GL_EQUAL
#define FUNC_NOTEQUAL GL_NOTEQUAL
#define FUNC_LEQUAL GL_LEQUAL
#define FUNC_GEQUAL GL_GEQUAL
#define FUNC_LESS GL_LESS
#define FUNC_GREATER GL_GREATER
#define FUNC_NEVER GL_NEVER
#define FUNC_ALWAYS GL_ALWAYS


#endif